# Generated by Django 5.2.15 on 2026-07-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_investorprofile_bio_investorprofile_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investorprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='country',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
