# Generated by Django 5.2.15 on 2026-07-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_email_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='entra_oid',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
