# Generated by Django 5.2.15 on 2026-07-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_recompact_person_handles'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorprofile',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
