# Generated by Django 5.2.15 on 2026-08-08 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_investorprofile_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorprofile',
            name='links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='manifesto',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='SelfDeclaredExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('started_on', models.DateField()),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_declared_experiences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_on'],
            },
        ),
    ]
