# Generated by Django 5.2.15 on 2026-09-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_firebase_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorprofile',
            name='city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='city_key',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
    ]
