# Generated by Django 5.2.15 on 2026-09-15 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messaging', '0006_user_block_rls'),
        ('orgs', '0025_alter_activity_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuilderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('adult_confirmed', models.BooleanField(default=False)),
                ('primary_strength', models.CharField(blank=True, choices=[('technical', 'Technical'), ('business', 'Business'), ('product', 'Product'), ('design', 'Design'), ('other', 'Other')], default='', max_length=20)),
                ('looking_for', models.JSONField(blank=True, default=list)),
                ('commitment', models.CharField(blank=True, choices=[('exploring', 'Exploring ideas'), ('nights', 'Nights & weekends'), ('full_time', 'Full-time')], default='', max_length=20)),
                ('sectors', models.JSONField(blank=True, default=list)),
                ('has_idea', models.BooleanField(default=False)),
                ('idea_pitch', models.CharField(blank=True, default='', max_length=280)),
                ('prompts', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='builder', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['is_active', 'primary_strength'], name='cofounder_b_is_acti_9b7c25_idx')],
            },
        ),
        migrations.CreateModel(
            name='CofounderInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cofounder_interests_sent', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cofounder_interests_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['target', 'liked'], name='cofounder_c_target__29d187_idx')],
                'constraints': [models.UniqueConstraint(fields=('actor', 'target'), name='uniq_cofounder_interest'), models.CheckConstraint(condition=models.Q(('actor', models.F('target')), _negated=True), name='no_self_cofounder_interest')],
            },
        ),
        migrations.CreateModel(
            name='CofounderMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('matched', 'Matched'), ('chatting', 'Chatting'), ('met', 'Met in person'), ('formed_org', 'Formed an organization'), ('archived', 'Archived')], default='matched', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='messaging.conversation')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='orgs.organization')),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cofounder_matches_a', to=settings.AUTH_USER_MODEL)),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cofounder_matches_b', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('user_a__lt', models.F('user_b'))), name='cofounder_match_ordered_pair'), models.UniqueConstraint(fields=('user_a', 'user_b'), name='uniq_cofounder_match')],
            },
        ),
    ]
