# Generated by Django 5.2.15 on 2026-07-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_payload_alter_notification_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('reaction', 'Reaction'), ('comment', 'Comment'), ('follower', 'Follower'), ('interest', 'Interest'), ('verification', 'Verification'), ('profile_views', 'Profile Views'), ('milestone', 'Milestone'), ('message', 'Message')], max_length=20),
        ),
    ]
