# Generated by Django 5.2.15 on 2026-09-03 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_notificationpreference_push_enabled_pushsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('reaction', 'Reaction'), ('comment', 'Comment'), ('follower', 'Follower'), ('interest', 'Interest'), ('verification', 'Verification'), ('profile_views', 'Profile Views'), ('milestone', 'Milestone'), ('pipeline', 'Pipeline'), ('connection_request', 'Connection Request'), ('connection_accepted', 'Connection Accepted'), ('mention', 'Mention'), ('broadcast', 'Broadcast')], max_length=20),
        ),
        migrations.CreateModel(
            name='NotificationBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('link', models.CharField(blank=True, default='', max_length=300)),
                ('target_all', models.BooleanField(default=True, help_text='If checked, ignores the user selection below and sends to every active user.', verbose_name='Send to all users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(blank=True, help_text="Only used when 'Send to all users' is unchecked.", related_name='received_broadcasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
