# Generated by Django 5.2.15 on 2026-09-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_alter_notification_kind_notificationbroadcast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('reaction', 'Reaction'), ('comment', 'Comment'), ('follower', 'Follower'), ('interest', 'Interest'), ('verification', 'Verification'), ('profile_views', 'Profile Views'), ('milestone', 'Milestone'), ('pipeline', 'Pipeline'), ('connection_request', 'Connection Request'), ('connection_accepted', 'Connection Accepted'), ('mention', 'Mention'), ('broadcast', 'Broadcast'), ('message', 'Message')], max_length=20),
        ),
    ]
