# Generated by Django 5.2.15 on 2026-09-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_alter_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='push_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
