# Generated by Django 5.2.15 on 2026-09-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0013_alter_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('reaction', 'Reaction'), ('comment', 'Comment'), ('follower', 'Follower'), ('interest', 'Interest'), ('verification', 'Verification'), ('profile_views', 'Profile Views'), ('milestone', 'Milestone'), ('pipeline', 'Pipeline'), ('connection_request', 'Connection Request'), ('connection_accepted', 'Connection Accepted'), ('mention', 'Mention'), ('broadcast', 'Broadcast'), ('message', 'Message'), ('job_application', 'Job Application'), ('application_interest', 'Application Interest'), ('job_expiring', 'Job Expiring'), ('affiliation_request', 'Affiliation Request'), ('affiliation_update', 'Affiliation Update'), ('investment_request', 'Investment Request'), ('investment_update', 'Investment Update')], max_length=20),
        ),
    ]
