# Generated by Django 5.2.15 on 2026-09-09 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0025_alter_activity_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_external_name', models.CharField(blank=True, default='', max_length=200)),
                ('amount_cents', models.BigIntegerField()),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('invested_on', models.DateField()),
                ('instrument', models.CharField(blank=True, default='', max_length=40)),
                ('status', models.CharField(choices=[('declared', 'Declared'), ('confirmed', 'Confirmed'), ('disputed', 'Disputed')], default='declared', max_length=10)),
                ('declarer_side', models.CharField(max_length=10)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('investor_public', models.BooleanField(default=False)),
                ('amount_public', models.BooleanField(default=False)),
                ('declarer_amount_public_intent', models.BooleanField(default=False)),
                ('confirmer_amount_public_intent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('declared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('investor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments_made', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments_received', to='orgs.organization')),
                ('round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments', to='orgs.fundraiseround')),
            ],
            options={
                'indexes': [models.Index(fields=['org', 'status'], name='investments_org_id_06c75a_idx'), models.Index(fields=['investor_user', 'status'], name='investments_investo_89d93a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('investor_external_name', ''), ('investor_user__isnull', False)), models.Q(('investor_user__isnull', True), models.Q(('investor_external_name', ''), _negated=True)), _connector='OR'), name='investment_investor_user_xor_external_name'), models.CheckConstraint(condition=models.Q(('amount_cents__gt', 0)), name='investment_amount_positive')],
            },
        ),
    ]
