# Generated by Django 5.2.15 on 2026-07-10 17:57

import django.db.models.deletion
import django.db.models.fields.json
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0011_alter_orgsection_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('company_registry', 'Company Registry'), ('founder_role', 'Founder Role'), ('tax_clearance', 'Tax Clearance'), ('ss_clearance', 'Ss Clearance'), ('annual_accounts', 'Annual Accounts'), ('stripe_traction', 'Stripe Traction'), ('open_banking', 'Open Banking'), ('saft_efatura', 'Saft Efatura')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('document_refs', models.JSONField(blank=True, default=list)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='orgs.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credibility_reviews', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['org', 'type', 'status'], name='credibility_org_id_412c8d_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'verified')), fields=('org', 'type'), name='uniq_verified_per_org_type'), models.UniqueConstraint(django.db.models.fields.json.KeyTextTransform('nif', 'payload'), condition=models.Q(('status', 'verified'), ('type', 'company_registry')), name='uniq_verified_nif_per_org')],
            },
        ),
    ]
