from django.urls import path

from . import public_seo_views, views

urlpatterns = [
    path("public/sitemap/", public_seo_views.PublicSitemapView.as_view()),
    path("public/discovery/", public_seo_views.PublicDiscoveryView.as_view()),
    path("public/orgs/<slug:slug>/", views.PublicOrgProfileView.as_view()),
    path("orgs/", views.OrgListCreateView.as_view()),
    path("orgs/<slug:slug>/", views.OrgProfileView.as_view()),
    path("orgs/<slug:slug>/onboarding/", views.OrgOnboardingView.as_view()),
    path("orgs/<slug:slug>/activate/", views.OrgActivateView.as_view()),
    path("orgs/<slug:slug>/insight/", views.OrgInsightView.as_view()),
    path("orgs/<slug:slug>/dataroom/", views.DataRoomView.as_view()),
    path("orgs/<slug:slug>/sections/", views.SectionListView.as_view()),
    path("orgs/<slug:slug>/sections/<str:kind>/fields/<str:key>/", views.SectionFieldView.as_view()),
    path("orgs/<slug:slug>/grants/", views.GrantListCreateView.as_view()),
    path("orgs/<slug:slug>/grants/<int:grant_id>/", views.GrantDetailView.as_view()),
    path("orgs/<slug:slug>/rounds/", views.RoundOpenView.as_view()),
    path("orgs/<slug:slug>/rounds/close/", views.RoundCloseView.as_view()),
    path("orgs/<slug:slug>/posts/", views.OrgPostsView.as_view()),
    path("orgs/<slug:slug>/posts/<int:activity_id>/", views.OrgPostDetailView.as_view()),
    path("orgs/<slug:slug>/posting-status/", views.OrgPostingStatusView.as_view()),
    path("orgs/<slug:slug>/feed/", views.FeedPostView.as_view()),
    path("orgs/<slug:slug>/feed/<int:activity_id>/", views.OrgActivityDetailView.as_view()),
    path("orgs/<slug:slug>/follow/", views.FollowOrgView.as_view()),
    path("orgs/<slug:slug>/logo/", views.OrgLogoView.as_view()),
    path("orgs/<slug:slug>/stats/", views.OrgStatsView.as_view()),
    path("orgs/<slug:slug>/members/", views.OrgMembersView.as_view()),
    path("orgs/<slug:slug>/members/<int:member_id>/", views.OrgMemberDetailView.as_view()),
    path(
        "orgs/<slug:slug>/members/<int:member_id>/skills/",
        views.MembershipSkillListCreateView.as_view(),
    ),
    path(
        "orgs/<slug:slug>/members/<int:member_id>/skills/<int:skill_id>/",
        views.MembershipSkillDetailView.as_view(),
    ),
    path(
        "orgs/<slug:slug>/members/<int:member_id>/skills/<int:skill_id>/confirm/",
        views.MembershipSkillConfirmView.as_view(),
    ),
    path("orgs/<slug:slug>/invites/", views.OrgInviteListCreateView.as_view()),
    path("orgs/<slug:slug>/invites/<int:invite_id>/", views.OrgInviteDetailView.as_view()),
    path("invites/<str:token>/accept/", views.OrgInviteAcceptView.as_view()),
    path("feed/", views.FeedView.as_view()),
    path("recent-org-updates/", views.RecentOrgUpdatesView.as_view()),
    path("trending/", views.TrendingView.as_view()),
    path("recommendations/", views.RecommendationView.as_view()),
    path("discovery/", views.DiscoveryView.as_view()),
    path("discovery/people/", views.DiscoverPeopleView.as_view()),
    path("discovery/advisors/", views.DiscoverAdvisorsView.as_view()),
]
