# Generated by Django 5.2.15 on 2026-07-13 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('orgs', '0016_alter_fundraiseround_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyOrgStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('new_followers_count', models.PositiveIntegerField(default=0)),
                ('profile_views_count', models.PositiveIntegerField(default=0)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='orgs.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['org', '-date'], name='analytics_d_org_id_346adc_idx')],
                'constraints': [models.UniqueConstraint(fields=('org', 'date'), name='uniq_daily_org_stats_per_day')],
            },
        ),
    ]
