# Generated by Django 5.2.15 on 2026-09-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_pipelineentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySiteStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('page_views', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SitePageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=300)),
                ('visitor_hash', models.CharField(db_index=True, max_length=32)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='pipelineentry',
            options={'ordering': ['-updated_at', '-id'], 'verbose_name': 'Pipeline entry', 'verbose_name_plural': 'Pipeline entries'},
        ),
        migrations.RenameIndex(
            model_name='activityfeedimpression',
            new_name='analytics_a_activit_6e48b6_idx',
            old_name='analytics_ac_activit_5f2c1a_idx',
        ),
        migrations.RenameIndex(
            model_name='personprofileview',
            new_name='analytics_p_subject_131542_idx',
            old_name='analytics_pe_subject_6e8b0d_idx',
        ),
        migrations.RenameIndex(
            model_name='pipelineentry',
            new_name='analytics_p_investo_e75494_idx',
            old_name='analytics_p_investo_6a0f8d_idx',
        ),
        migrations.AddIndex(
            model_name='sitepageview',
            index=models.Index(fields=['path', '-viewed_at'], name='analytics_s_path_116b39_idx'),
        ),
    ]
