# Generated by Django 5.2.15 on 2026-07-01 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_fundraising', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stage', models.CharField(blank=True, max_length=20)),
                ('sector', models.CharField(blank=True, max_length=50)),
                ('geo', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FundraiseRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuation', models.BigIntegerField(blank=True, null=True)),
                ('ask_amount', models.BigIntegerField(blank=True, null=True)),
                ('use_of_funds', models.TextField(blank=True)),
                ('stage', models.CharField(choices=[('pre_seed', 'Pre Seed'), ('seed', 'Seed'), ('series_a', 'Series A')], max_length=20)),
                ('is_open', models.BooleanField(default=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orgs.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrgSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('about', 'About'), ('team', 'Team'), ('products', 'Products'), ('market_thesis', 'Market Thesis'), ('news', 'News'), ('milestones', 'Milestones'), ('events', 'Events'), ('awards', 'Awards'), ('press', 'Press'), ('valuation', 'Valuation'), ('ask', 'Ask'), ('use_of_funds', 'Use Of Funds'), ('financials', 'Financials'), ('dataroom', 'Data Room'), ('cap_table', 'Cap Table')], max_length=30)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('private', 'Private')], default='public', max_length=12)),
                ('position', models.PositiveIntegerField(default=0)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='orgs.organization')),
            ],
            options={
                'unique_together': {('org', 'kind')},
            },
        ),
        migrations.CreateModel(
            name='OrgField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.JSONField()),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('private', 'Private')], default='public', max_length=12)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='orgs.orgsection')),
            ],
            options={
                'unique_together': {('section', 'key')},
            },
        ),
        migrations.CreateModel(
            name='RestrictedAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(max_length=50)),
                ('section_kind', models.CharField(max_length=30)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.organization')),
                ('viewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VisibilityGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_type', models.CharField(choices=[('user', 'User'), ('org', 'Org'), ('role', 'Role')], max_length=10)),
                ('principal_id', models.CharField(max_length=100)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.orgfield')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.organization')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.orgsection')),
            ],
        ),
        migrations.CreateModel(
            name='OrgMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='orgs.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('org', 'user')},
            },
        ),
    ]
