# Generated by Django 5.2.15 on 2026-07-05 17:53

from django.db import migrations, models


def set_existing_orgs_live(apps, schema_editor):
    """Orgs created before this feature shipped were already public — treat
    them as if they'd already gone through activation, so this migration
    doesn't silently un-publish every existing org."""
    Organization = apps.get_model("orgs", "Organization")
    Organization.objects.update(status="live")


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_organization_logo_orgfield_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='one_liner',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AddField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('live', 'Live')], default='draft', max_length=12),
        ),
        migrations.RunPython(set_existing_orgs_live, migrations.RunPython.noop),
    ]
