# Generated by Django 5.2.15 on 2026-07-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0008_reverify_org_owner_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='orginvite',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orginvite',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
