# Generated by Django 5.2.15 on 2026-07-08 13:15

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0009_orginvite_expires_at_orginvite_max_uses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='geo',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_fundraising',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='sector',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='organization',
            name='stage',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('live', 'Live')], db_index=True, default='draft', max_length=12),
        ),
        migrations.AlterField(
            model_name='orgfield',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='restrictedaccesslog',
            index=models.Index(fields=['org', 'section_kind', '-accessed_at'], name='orgs_restri_org_id_40ecc9_idx'),
        ),
    ]
