# Generated by Django 5.2.15 on 2026-07-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0010_alter_organization_geo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgsection',
            name='kind',
            field=models.CharField(choices=[('about', 'About'), ('team', 'Team'), ('products', 'Products'), ('market_thesis', 'Market Thesis'), ('links', 'Links'), ('certified_financials', 'Certified Financials'), ('news', 'News'), ('milestones', 'Milestones'), ('events', 'Events'), ('awards', 'Awards'), ('press', 'Press'), ('valuation', 'Valuation'), ('ask', 'Ask'), ('use_of_funds', 'Use Of Funds'), ('financials', 'Financials'), ('dataroom', 'Data Room'), ('cap_table', 'Cap Table')], max_length=30),
        ),
    ]
