# Generated by Django 5.2.15 on 2026-07-13 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0011_alter_orgsection_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('news', 'News'), ('milestones', 'Milestones'), ('events', 'Events'), ('awards', 'Awards'), ('press', 'Press'), ('update', 'Update')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/')),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('private', 'Private')], default='public', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reaction_count', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('source_org_field_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('source_investor_post_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='orgs.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['org', '-occurred_at'], name='orgs_activi_org_id_d72ed1_idx'), models.Index(fields=['author', '-occurred_at'], name='orgs_activi_author__8c5cb5_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('org__isnull', False), ('author__isnull', False), _connector='OR'), name='activity_has_a_subject')],
            },
        ),
    ]
