# Generated by Django 5.2.15 on 2026-07-13 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0015_backfill_member_follows'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundraiseround',
            options={'ordering': ['-opened_at']},
        ),
        migrations.AddField(
            model_name='fundraiseround',
            name='raised_amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fundraiseround',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundraise_rounds', to='orgs.organization'),
        ),
    ]
