# Generated by Django 5.2.15 on 2026-07-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0016_alter_fundraiseround_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
