# Generated by Django 5.2.15 on 2026-08-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0021_recompact_org_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orginvite',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member'), ('advisor', 'Advisor'), ('board', 'Board member'), ('fractional', 'Fractional executive')], default='member', max_length=20),
        ),
        migrations.AlterField(
            model_name='orgmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member'), ('advisor', 'Advisor'), ('board', 'Board member'), ('fractional', 'Fractional executive')], default='member', max_length=20),
        ),
    ]
