# Generated by Django 5.2.15 on 2026-08-08 22:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0022_alter_orginvite_role_alter_orgmembership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgmembership',
            name='ended_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orgmembership',
            name='started_on',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='MembershipSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('declared', 'Declared'), ('org_confirmed', 'Org Confirmed')], default='declared', max_length=14)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_used', to='orgs.orgmembership')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('membership', 'skill'), name='uniq_membership_skill')],
            },
        ),
    ]
