# Generated by Django 5.2.15 on 2026-08-12 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0023_orgmembership_ended_on_orgmembership_started_on_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollow',
        ),
    ]
