# Generated by Django 5.2.15 on 2026-09-07 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0024_delete_userfollow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
