# Generated by Django 5.2.15 on 2026-09-08 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0025_alter_activity_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('founder', 'Founder'), ('employee', 'Employee'), ('contractor', 'Contractor'), ('volunteer', 'Volunteer'), ('advisor', 'Advisor')], max_length=12)),
                ('title', models.CharField(blank=True, default='', max_length=120)),
                ('started_on', models.DateField()),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('self_declared', 'Self Declared'), ('pending', 'Pending'), ('verified', 'Verified'), ('disputed', 'Disputed')], default='pending', max_length=14)),
                ('verified_via', models.CharField(blank=True, choices=[('org', 'Org'), ('registry', 'Registry')], default='', max_length=10)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='orgs.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['org', 'status'], name='affiliation_org_id_27d87a_idx'), models.Index(fields=['user'], name='affiliation_user_id_782025_idx')],
            },
        ),
    ]
