# Generated by Django 5.2.15 on 2026-09-07 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0025_alter_activity_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=6000)),
                ('role_area', models.CharField(blank=True, default='', max_length=60)),
                ('engagement_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship'), ('volunteer', 'Volunteer'), ('cofounder', 'Co-founder'), ('advisor', 'Advisor')], max_length=20)),
                ('location_type', models.CharField(choices=[('onsite', 'On-site'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], max_length=10)),
                ('location_city', models.CharField(blank=True, default='', max_length=80)),
                ('salary_text', models.CharField(blank=True, default='', max_length=120)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed')], db_index=True, default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('renewed_at', models.DateTimeField(blank=True, null=True)),
                ('renewal_count', models.PositiveIntegerField(default=0)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='orgs.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobCompensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('salary', 'Salary'), ('equity', 'Equity'), ('stock_options', 'Stock options'), ('revenue_share', 'Revenue share'), ('other', 'Other')], max_length=20)),
                ('detail', models.CharField(blank=True, default='', max_length=200)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation', to='jobs.jobpost')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, default='', max_length=1500)),
                ('external_link', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('viewed', 'Viewed'), ('interested', 'Interested'), ('declined', 'Declined'), ('hired', 'Hired')], db_index=True, default='applied', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobpost')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['status', '-created_at'], name='jobs_jobpos_status_de3a0d_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['engagement_type', 'location_type'], name='jobs_jobpos_engagem_598092_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobcompensation',
            constraint=models.UniqueConstraint(fields=('job', 'kind'), name='uniq_job_comp_kind'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('job', 'applicant'), name='uniq_application'),
        ),
    ]
