# Generated by Django 5.2.15 on 2026-09-08 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_connections_rls'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrgConnectionRequest',
        ),
    ]
