# Generated by Django 5.2.15 on 2026-08-26 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0024_delete_userfollow'),
        ('social', '0005_eventparticipation_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('url_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('image_url', models.URLField(blank=True, default='', max_length=2000)),
                ('site_name', models.CharField(blank=True, default='', max_length=200)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='orgs.activity')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions_made', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='social.comment')),
                ('target_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentions_received', to='orgs.organization')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['target_user', '-created_at'], name='social_ment_target__89128e_idx'), models.Index(fields=['target_org', '-created_at'], name='social_ment_target__39fd26_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('activity__isnull', False), ('comment__isnull', True)), models.Q(('activity__isnull', True), ('comment__isnull', False)), _connector='OR'), name='mention_belongs_to_exactly_one_container'), models.CheckConstraint(condition=models.Q(models.Q(('target_org__isnull', True), ('target_user__isnull', False)), models.Q(('target_org__isnull', False), ('target_user__isnull', True)), _connector='OR'), name='mention_targets_exactly_one_kind')],
            },
        ),
    ]
