# Generated by Django 5.2.15 on 2026-09-15 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_user_block_rls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagereport',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='messaging.conversation'),
        ),
    ]
